# Generated by Django 5.2.5 on 2025-08-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_dueño')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del dueño')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del dueño')),
                ('telefono', models.IntegerField(verbose_name='Teléfono del dueño')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico del dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_mascota')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie del animal')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo del animal')),
                ('edad', models.IntegerField(default=0, verbose_name='Edad del animal')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_turno')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del turno')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la consulta')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.dueño')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.mascota')),
            ],
        ),
    ]
